### ISSUE TITLE
Vocabulary styles being overriden by custom styling

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cc-chooser#31]
Due to issues with specificity, styling provided by CC Vocabulary is being overriden by styling from other third-party libraries and custom written CSS, leading to a different UI than what is expected. This is causing components to look broken or erratically styled.

**To Reproduce**
1. Check out the branch from PR #30
1. Run the development server

**Expected behavior**
The components should render like the examples in the Vocabulary [styleguide](https://creativecommons.github.io/cc-vocabulary/styleguide).

**Screenshots**
![image](https://user-images.githubusercontent.com/16580576/64158941-0140a080-ce57-11e9-99b2-40258638c419.png)
^ Broken `Footer` and `Locale`
![image](https://user-images.githubusercontent.com/16580576/64158898-ed953a00-ce56-11e9-9ea2-a4e91f421f9b.png)
^ Expected `Footer` and `Locale`

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 30)
 - Browser: Firefox
 - Version: 68

**Comment by deboragaleano** [comment]
Hi @akmadian, I'm an Outreachy applicant. I will try to work on this. Thank you!

**Comment by dhruvkb** [comment]
I’m happy to help anywhere Vocabulary usage is involved!

**Comment by akmadian** [comment]
Go ahead! @deboragaleano

**Comment by onyijne** [comment]
Hi @akmadian can I work on this too?

**Comment by akmadian** [comment]
Sorry, @onyijne, this issue is already being worked on by someone else. Keep checking back on the repository cause I'll be adding more issues soonish. Any issue with the `in progress` tag is already being worked on by someone else.

**Comment by onyijne** [comment]
Okay @akmadian I understand how it works now, thanks.

**Comment by deboragaleano** [comment]
So sorry but I won't be able to work on this issue in the end. I believe @onyijne can take it now :) Thank you!

**Comment by onyijne** [comment]
It's okay @deboragaleano, @akmadian can I go ahead?

**Comment by akmadian** [comment]
Yep, go ahead @onyijne :)

**Comment by onyijne** [comment]
@dhruvkb please how can I access the @creativecommons/vocabulary dir. can't seem to locate it.
![Opera Snapshot_2019-10-07_133103_localhost](https://user-images.githubusercontent.com/6826336/66313057-a0026600-e909-11e9-9e2a-8b108181e1df.png)
This is what I have now, can't find the Footer component to enable me edit the first two parts.

**Comment by onyijne** [comment]
Okay my IDE kinda hid the dir, but how do I effect push change in the vocabulary package since it's in vendors dir?

**Comment by onyijne** [comment]
Okay my IDE kinda hid the dir, but how do I push changes I'll make in the vocabulary package since it's in node_modules dir?

**Comment by akmadian** [comment]
Either make a pull request to the cc-vocabulary repo with your changes (make sure they don't break anything else in vocabulary), or make changes to the CSS in components that need attention in the cc-chooser source (this option is far better in my opinion). For the footer, your CSS mods should be in the App.vue parent component.

**Comment by onyijne** [comment]
@akmadian I might have to make a pull request to the  cc-vocabulary repo as the footer requires more than CSS, the wording and logo needs modification. However, if you do not recommend making a pull request to  cc-vocabulary repo, and would permit me to I can use DOM manipulation to effect the changes.

**Comment by akmadian** [comment]
I was saying that (maybe I could have been more clear), chances are that there's some CSS within the chooser that's causing issues with vocab components, and that it's better to find the problematic CSS and fix it instead of modifying vocabulary in node_modules. 

Although, it sounds like you may have found a deeper issue with vocabulary. So, if you've got a fix for that issue, and it happens to also fix this one, then that sounds better to me. If you did find a deeper issue, I would definitely submit a PR to vocab, then do what's needed to fix the issue in the chooser if it still needs some work.

**Comment by onyijne** [comment]
I 

> Due to issues with specificity, styling provided by CC Vocabulary is being overriden by styling from other third-party libraries and custom written CSS, leading to a different UI than what is expected. This is causing components to look broken or erratically styled.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Check out the branch from PR #30
> 2. Run the development server
> 
> **Expected behavior**
> The components should render like the examples in the Vocabulary [styleguide](https://creativecommons.github.io/cc-vocabulary/styleguide).
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/16580576/64158941-0140a080-ce57-11e9-99b2-40258638c419.png)
> ^ Broken `Footer` and `Locale`
> ![image](https://user-images.githubusercontent.com/16580576/64158898-ed953a00-ce56-11e9-9ea2-a4e91f421f9b.png)
> ^ Expected `Footer` and `Locale`
> 
> **Desktop (please complete the following information):**
> 
> * OS: Linux (Fedora 30)
> * Browser: Firefox
> * Version: 68

Looking at the contents on the images for broken and that of expected, they are different. This is what I was actually referring to, and intended to harmonize.
![Opera Snapshot_2019-10-07_133103_localhost](https://user-images.githubusercontent.com/6826336/66484742-809d4180-ea9f-11e9-9dc6-e7b4aed7d727.png)
This is what I have done so far

**Comment by akmadian** [comment]
Ah, I see where the confusion is. The content of the footer is not supposed to exactly match the expected footer. The links above the locale selector are meant to be customizable, along with other parts of the footer component. The only real CSS bug I saw in the footer was the weird padding/ alignment of elements in the local selector.
I’ll give some feedback on content in the PR thread. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by onyijne** [comment]
Okay, for the weird padding of the local selector, I think I have fixed
that. So I'll just remove WIP if that's all that's needed for now, while I
wait for the feedback you'll get from the PR thread.
