### ISSUE TITLE
Write tests for Chooser component

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cc-chooser#33]
**Describe the solution you'd like**
Unit tests need to be written for the [Chooser components](https://github.com/creativecommons/cc-chooser/tree/master/src/components). Add them to this directory [here](https://github.com/creativecommons/cc-chooser/tree/master/test/unit/specs/components) 

The frameworks being used are [Jest](https://jestjs.io/) and [Vue Test Utils](https://vue-test-utils.vuejs.org/)

**Additional context**
Please comment on this issue to tell us that you're interested in working on it before getting started!

**Comment by HAMZABoxer98** [comment]
I want to work on this @akmadian.

**Comment by amitkumarrathore** [comment]
Hey i want to work on it @akmadian

**Comment by HAMZABoxer98** [comment]
@amitkumarrathore I have a sent a PR for this.

**Comment by akmadian** [comment]
I'm going to assign this to @amitkumarrathore because @HAMZABoxer98 has already submitted a PR for #37. Go ahead and get started, Amit!

**Comment by amitkumarrathore** [comment]
I am totally new here. how can i fix them @akmadian

**Comment by akmadian** [comment]
Hey @amitkumarrathore, sorry it took so long for me to get back to you. I'll defer you to @brenoferreira, he'll help out :)

**Comment by brenoferreira** [comment]
For those interested in helping, I'd recommend taking a look at the following:

* The Vue Test Utils Getting Started Guide: https://vue-test-utils.vuejs.org/guides/#getting-started
* The code of some of the existing tests [here](https://github.com/creativecommons/cc-chooser/tree/master/test/unit/specs/components)
* You can also see some of the tests available in the CC Search frontend [here](https://github.com/creativecommons/cccatalog-frontend/tree/develop/test/unit/specs/components)

This should give you an idea of how to write some useful tests.

**Comment by akmadian** [comment]
Hey @amitkumarrathore, this is a heads up that I may free up this issue so others can have a shot if you don't show signs that you're working on this issue in the next 4-5 days.

**Comment by khansaAmrouni** [comment]
Hi! I am an outreachy applicant! is it possible to contribute by fixing this issue

**Comment by akmadian** [comment]
Go ahead, @khansaAmrouni!

**Comment by akmadian** [comment]
Hey @khansaAmrouni, if I don't see any progress on this issue in the next two days, I'll have to free it up for someone else to work on it.

**Comment by khansaAmrouni** [comment]
hey!  please free it up, i won't work on this issue, i am sorry

**Comment by alessandrodolci** [comment]
Hi there, I'd like to work on this, are you fine with it? I'm taking a look at the code right now!

**Comment by akmadian** [comment]
Yep, go ahead! @alessandrodolci
