### ISSUE TITLE
Write tests for CopyButton component

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cc-chooser#34]
**Describe the solution you'd like**
e2e and unit tests need to be written for the CopyButton.vue component (`./src/components/CopyButton.vue`). Please write e2e tests in a new file named CopyButton.js in `./test/e2e/specs/`, and unit tests in a new file named CopyButton.specs.js in `./test/unit/specs/`. 

The frameworks being used are (Jest)[https://jestjs.io/] for unit testing, and the (nightwatch.js)[https://nightwatchjs.org/] for e2e testing.

**Additional context**
Please comment on this issue to tell us that you're interested in working on it before getting started!

**Comment by priscilauchoa** [comment]
I'm interested in working on this issues.

**Comment by onyijne** [comment]
Hi @akmadian I'm an Outreachy Intern applicant, can I work on this?

**Comment by akmadian** [comment]
Sorry, @onyijne, Priscila is already working on this issue :/
