### ISSUE TITLE
Write tests for HelpSection component

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cc-chooser#35]
**Describe the solution you'd like**
e2e and unit tests need to be written for the HelpSection.vue component (`./src/components/HelpSection.vue`). Please write e2e tests in a new file named HelpSection.js in `./test/e2e/specs/`, and unit tests in a new file named HelpSection.specs.js in `./test/unit/specs/`. 

The frameworks being used are (Jest)[https://jestjs.io/] for unit testing, and the (nightwatch.js)[https://nightwatchjs.org/] for e2e testing.

**Additional context**
Please comment on this issue to tell us that you're interested in working on it before getting started!

**Comment by Joranhezon** [comment]
Hi! I'd like to work on this issue.

**Comment by akmadian** [comment]
Go ahead! @Joranhezon
