### ISSUE TITLE
Write tests for HTMLGenerator component

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cc-chooser#36]
**Describe the solution you'd like**
e2e and unit tests need to be written for the HTMLGenerator.vue component (`./src/components/HTMLGenerator.vue`). Please write e2e tests in a new file named HTMLGenerator.js in `./test/e2e/specs/`, and unit tests in a new file named HTMLGenerator.specs.js in `./test/unit/specs/`. 

The frameworks being used are (Jest)[https://jestjs.io/] for unit testing, and the (nightwatch.js)[https://nightwatchjs.org/] for e2e testing.

**Additional context**
Please comment on this issue to tell us that you're interested in working on it before getting started!

**Comment by obulat** [comment]
Hi! I am interested in writing this test.

**Comment by akmadian** [comment]
Hey @obulat, you’re all clear to start working on this issue!

**Comment by alexido19** [comment]
I'm Alexander from Outreachy I'm looking for a first timers issue here

**Comment by akmadian** [comment]
@alexido19 All of the issues in this repo are already being worked on by others. Please look for other issues marked with the `help wanted`, `good first issue`, and/or `outreachy` tags in other CC repos. Issues with the yellow `in progress` tag are already claimed and are not up for grabs.
