### ISSUE TITLE
Write tests for IconSelector component

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cc-chooser#37]
**Describe the solution you'd like**
e2e and unit tests need to be written for the IconSelector.vue component (`./src/components/IconSelector.vue`). Please write e2e tests in a new file named IconSelector.js in `./test/e2e/specs/`, and unit tests in a new file named IconSelector.specs.js in `./test/unit/specs/`. 

The frameworks being used are (Jest)[https://jestjs.io/] for unit testing, and the (nightwatch.js)[https://nightwatchjs.org/] for e2e testing.

**Additional context**
Please comment on this issue to tell us that you're interested in working on it before getting started!

**Comment by HAMZABoxer98** [comment]
Hi @akmadian, I think I am ready to fix this.

**Comment by HAMZABoxer98** [comment]
Hi @akmadian, I think I am ready to fix this.

**Comment by akmadian** [comment]
Go ahead! Please remember two write both e2e and unit tests :)
