### ISSUE TITLE
Legal review of text in chooser site

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cc-chooser#56]
This is a thread of changes to make to the text in the chooser to ensure that all legal requirements are fulfilled.

**Comment by akmadian** [comment]
**From Diane**
we don't want to use the word "tweak", in any description of how ND and the non ND licenses work. Wherever that appears, I recommend we change it to "adapt", because ND does in fact allow tweaking just so long as an adaptation/derivative is not made. That's a language change throughout that could be made that isn't controversial.

**Comment by peterspdx** [comment]
@akmadian Is this the private wiki? Just want to double check.

**Comment by akmadian** [comment]
@peterspdx Nope, this is public
