### ISSUE TITLE
Feedback Form

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cc-chooser#61]
Before the blog post, a Google Form needs to be made to take user feedback about the new chooser. A Vue component will also need to be made for linking to this form.

**Comment by akmadian** [comment]
Kriti will make form, send me link, and I'll make Vue component.

**Comment by akmadian** [comment]
Component and styling done, waiting for form link

**Comment by kgodey** [comment]
@akmadian I shared the form with you via email.
