### ISSUE TITLE
When using npm run serve on fresh clone, get dependency not found error.

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cc-chooser#74]
**Describe the bug**
When using a fresh clone of the repo, on the `WIP-Redesign` and `AttributionDetails` branches, and running `npm run serve`, after running `npm i`, I get
```
ERROR  Failed to compile with 1 errors
This dependency was not found:

* @fortawesome/free-solid-svg-icons in ./src/main.js

To install it, you can run: npm install --save @fortawesome/free-solid-svg-icons
```
This package probably just got lost from package.json in the transition to Vue cli, no big deal :)

**To Reproduce**
1. Clone repo, and switch to `AttributionDetails` or `WIP-Redesign` branch
2. Run `npm i`
3. Run `npm run serve`

**Desktop (please complete the following information):**
 - OS: Windows 10 1809 17763.914
 - npm version: 6.4.1
 - node version: 10.15.3

**Comment by obulat** [comment]
Thank you, I wouldn't notice it on my own:) 
My latest commit (actually, three commits) to `WIP-redesign` branch adds the  `@fortawesome/free-solid-svg-icons`, as well as updating the `@creativecommons/vocabulary` imports after the latest split of vue-vocabulary package from vocabulary one.
