### ISSUE TITLE
Dependency issues with vue-vocab and vocab on fresh clone of yes-no-change branch

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cc-chooser#76]
**Describe the bug**
The versions of both vocabulary and vue-vocabulary required in package.json are not in the npm registry. I tried manually updating both to most current (0.0.0-alpha.30 for both), and then started getting import and dependency not found errors. One of these errors was specifically for `@creativecommons/vocabulary/css/vocabulary.css`.

My guess is that you were working with vocab versions that have since been deprecated, and (for some reason) taken off of npm, and that there are now breaking changes in 0.0.0-alpha.30, which breaks imports and other dependency related stuff :/

**To Reproduce**
1. Clone repo
2. Switch to `yes-no-change` branch
3. Run `npm i`

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 1809 17763.973
 - npm version: 6.13.6
 - node version: 12.14.1

**Comment by obulat** [comment]
The problem was with renaming `vocabulary.css` into `index.css`. With the latest commit it should be solved.

**Comment by akmadian** [comment]
That was it!
