### ISSUE TITLE
Some things I didn't catch in last review

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cc-chooser#85]
Hey Olga, I missed some things in the last review. I was on mobile and everything looked good so I approved. Please submit another PR with the following fixes:
 - Please add the following tags for mobile home screen shortcut icons:
    - `<link rel="icon" type="image/png" href="https://d15omoko64skxi.cloudfront.net/wp-content/uploads/2016/05/cc-site-icon-300x300.png" sizes="192x192">`
    - `<link rel="apple-touch-icon-precomposed" href="https://d15omoko64skxi.cloudfront.net/wp-content/uploads/2016/05/cc-site-icon-300x300.png">`
 - Change og:title content to "Choose a License"
 - Add `<meta property="of:type" content="website">`
 - Please change og:description to "Want to license your work with Creative Commons, but not sure where to start, or which license is right for you? Use our license chooser!"
 - Change og:url to `https://beta-chooser.creativecommons.org`
 - The og:image content currently points to a screenshot for the CC WP plugin, please change to the CC logo for now.
 - Change twitter:site to `creativecommons.org`
 - There's a typo in the noscript section, "hello doesn't work properly"

**Comment by obulat** [comment]
Thank you for detailed review, Ari. I've changed everything except for twitter:site: the [twitter guide](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started) states that a twitter handle should be used there: 

> twitter:site | @username for the website used in the card footer.
>  Indicates the Twitter account for the website or platform on which the content was published. Note that a service may set separate Twitter accounts for different pages/sections of their website, and the most appropriate Twitter account should be used to provide the best context for the user.

What is the most appropriate handle for that?

**Comment by akmadian** [comment]
Ah I see, I assumed that the creator meta would be for that purpose. @creativecommons should be best. Go ahead and submit a PR with your changes and I'll take a look

**Comment by obulat** [comment]
I assumed that, too, at first. It's nice they have examples.
