### ISSUE TITLE
Removing the "Free Cultural Works" Designation

### ISSUE THREAD

**Issue by kalendar** [creativecommons/cc-chooser#87]
Why are we dragging forward the Free Cultural Works designation in the license chooser? 

Ostensibly, the chooser is used by **novice users** who need to be taken step by step through each of the considerations involved in choosing a CC license. Why confuse that already daunting process with this icon and link? The icon and link appear with no context in the "Your License" pane on the right. Providing the necessary context for them would only further complicate things for novice users. In teaching 1000s of people about Creative Commons over the years I have seen many people get confused when they encounter the FCW icon / link in the middle of the license chooser process. 

We have a rare opportunity to remove a large source of confusion from the license selection process. I believe we should remove the icon and link.

**Comment by akmadian** [comment]
Hello and thank you for bringing this to our attention. We will be discussing this in the next week or so and will get back to you about it soon!

**Comment by akmadian** [comment]
Hey @kalendar, the discussion about this is currently ongoing. There is currently no deadline for a decision, but one will be made either way before the new chooser is released. Please feel free to ping me if you've got any questions :)

**Comment by OUDcollective** [comment]
I am a year new to the digital creative community; and not that it counts for much, but, I rather like the Free Cultural Works Designation as it does have a purpose; psychological but there is purpose. 

As for me, it was the first thing that stood out with the CC BY 4.0 making me curious to learn more while now checking footers on websites to see how they share. 

Also, great job with the license chooser; would love to someday become proficient enough to help develop an extension, as the most arduous part of using the licensing is the shuffling around trying to make sure you have the license linked properly and tagged. That and the wording; as simple as it is; it's daunting when you're all new and trying learn all things 2020 digital skills.

This will definitely make for an amazing extension, certainly you all are already considering this. Thanks CC community for all the good things you are doing. 

Best,

[C-Brennan-Poole](https://www.crunchbase.com/person/c-brennan-poole/)
[Chasing the Wind](https://www/crunchbase.com/organization/chasing-the-wind-llc/)

**Comment by akmadian** [comment]
Hello all! We've decided to go for a middle ground and still include the opportunity to learn about free culture licenses and free cultural works through the help section. This can be found on the right side of the site, under the "Confused? Need Help?" section, through clicking on "What is a Free Culture License?".

We think that this approach, while still providing the ability to learn more, and even adding more information about FCW, reduces clutter and keeps the license selection process simple and easy.

I'm going to close this issue, but I'll be notified of any new posts in the this thread in case you have any questions :)

**Comment by fkohrt** [comment]
I find it very unfortunate that by now you have opted to completely remove the "Free Cultural Works" designation, not only from the sidebar but also from the help section (117d4c2). I had hoped a more balanced approach would be taken when weighing simplicity against teaching about the public commons. The NC and ND restrictions _do_ make a difference and it we have [come](https://en.wikipedia.org/wiki/Budapest_Open_Access_Initiative) a [long](https://en.wikipedia.org/wiki/Bethesda_Statement_on_Open_Access_Publishing) [way](https://en.wikipedia.org/wiki/Berlin_Declaration_on_Open_Access_to_Knowledge_in_the_Sciences_and_Humanities) to make this recognition.
